apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-manager-load-config
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: catalog-manager
data:
  catalog-manager-sql-script.yaml: |
    steps:
    - name: "creation-step"
      timeout: "5s"
      queries:
        - CREATE SCHEMA IF NOT EXISTS catalog;
        - CREATE TABLE IF NOT EXISTS catalog.users (
            username VARCHAR(50) PRIMARY KEY NOT NULL,
            salt VARCHAR(16) NOT NULL,
            salted_password VARCHAR(256) NOT NULL
          );
