apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-manager-pv-claim
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: catalog-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi