apiVersion: v1
kind: Service
metadata:
  name: catalog-manager
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: catalog-manager
spec:
  selector:
     app: catalog-manager
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7060
      targetPort: 7060