apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-provider-config
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: catalog-manager
data:
  provider_config.config: |-
    [
    {
    "name":"catalog",
    "url":"git@github.com:kubenapp/catalog.git",
    "provider":"github",
    "ssh_path":"/napptive/ssh/id_rsa"
    }
    ]