apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: elastic
data:
  elasticsearch.yml: |-
    path.data: /data
    network.host: 0.0.0.0
    cluster.name: TARGET_K8S_NAMESPACE