name: Publish latest component version

on:
  push:
    branches: [main]
jobs:
  build:
    name: Push docker images
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push Docker images
        run: make docker-push
        env:
          VERSION: latest
          TARGET_DOCKER_REGISTRY: napptive

  # security Job, checks vulnerabilities      
  security-scan:
    name: Scan vulnerabilities
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Get Repo name
      id: name
      run: echo "::set-output name=name::${GITHUB_REPOSITORY}"

     # Scan vulnerabilities with tivy
    - name: Vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ steps.name.outputs.name }}:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    # Upload rersults to Github Security tab
    - name: Upload scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
